### ISSUE TITLE
Update favicon with the new logo

### ISSUE THREAD

**Issue by equinusocio** [contactlab/design-system#44]
We need to fix the site favicon with the new team logo:
![https://camo.githubusercontent.com/5f31396bfe83ed6575bd4474fb48ac11885096d0/68747470733a2f2f75782e636f6e746163746c61622e636f6d2f6173736574732f696d616765732f5558442e737667](https://camo.githubusercontent.com/5f31396bfe83ed6575bd4474fb48ac11885096d0/68747470733a2f2f75782e636f6e746163746c61622e636f6d2f6173736574732f696d616765732f5558442e737667)

**Comment by gargalloa** [comment]
fixed.

**Comment by equinusocio** [comment]
Where is the commit @gargalloa
